version: 2
jobs:
  build:
    working_directory: ~/workspace/clockwork
    docker:
      - image: circleci/golang:1.13.8
    steps:
      - checkout
      - run:
          name: test
          command: go test -v -race
      - run:
          name: fmt
          command: go fmt
      - run:
          name: check-diff
          command: git diff --quiet
